// <auto-generated />
using System;
using InkManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InkManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423013420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InkManager.Core.Entities.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstudioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EstudioId");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Asistente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermisosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Asistentes");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Adelanto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<int?>("AsistenteId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaRecordatorioEnviado")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoReferenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotasInternas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotasPublicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiereRecordatorio")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TamanioCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZonaCuerpoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsistenteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaHoraInicio");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FechaHoraInicio"), new[] { "Estado", "ArtistaId" });

                    b.HasIndex("ZonaCuerpoId");

                    b.HasIndex("ArtistaId", "Estado");

                    b.ToTable("Citas", t =>
                        {
                            t.HasCheckConstraint("CK_Cita_Estado", "Estado IN ('pendiente', 'confirmada', 'en_curso', 'completada', 'cancelada', 'no_asistio')");
                        });
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlergiasConocidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NotasGenerales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("InkManager.Core.Entities.ConfiguracionCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiasAntelacionRecordatorio")
                        .HasColumnType("int");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("EmailEnvio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstudioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HorarioRecordatorio")
                        .HasColumnType("time");

                    b.Property<string>("PasswordEncriptada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UsarSSL")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EstudioId");

                    b.ToTable("ConfiguracionesCorreo");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cubiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ArtistaAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<int>("EstudioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PosicionX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PosicionY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PosicionZ")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaAsignadoId");

                    b.HasIndex("EstudioId");

                    b.ToTable("Cubiculos");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfiguracionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("InkManager.Core.Entities.HistorialEstadoCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("HistorialEstadosCita");
                });

            modelBuilder.Entity("InkManager.Core.Entities.MetricaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<int>("EstudioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCitasCompletadas")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("EstudioId");

                    b.ToTable("MetricasDiarias");
                });

            modelBuilder.Entity("InkManager.Core.Entities.PagoParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("PagosParciales", t =>
                        {
                            t.HasCheckConstraint("CK_PagoParcial_MetodoPago", "MetodoPago IN ('efectivo', 'tarjeta', 'transferencia', 'otro')");
                        });
                });

            modelBuilder.Entity("InkManager.Core.Entities.ZonaCuerpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoordenadasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZonasCuerpo");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Artista", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Estudio", "Estudio")
                        .WithMany("Artistas")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Asistente", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Artista", "Artista")
                        .WithMany("Asistentes")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cita", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Artista", "Artista")
                        .WithMany("Citas")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InkManager.Core.Entities.Asistente", "Asistente")
                        .WithMany("Citas")
                        .HasForeignKey("AsistenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InkManager.Core.Entities.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InkManager.Core.Entities.ZonaCuerpo", "ZonaCuerpo")
                        .WithMany("Citas")
                        .HasForeignKey("ZonaCuerpoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artista");

                    b.Navigation("Asistente");

                    b.Navigation("Cliente");

                    b.Navigation("ZonaCuerpo");
                });

            modelBuilder.Entity("InkManager.Core.Entities.ConfiguracionCorreo", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Estudio", "Estudio")
                        .WithMany("ConfiguracionesCorreo")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cubiculo", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Artista", "ArtistaAsignado")
                        .WithMany("CubiculosAsignados")
                        .HasForeignKey("ArtistaAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InkManager.Core.Entities.Estudio", "Estudio")
                        .WithMany("Cubiculos")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistaAsignado");

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("InkManager.Core.Entities.HistorialEstadoCita", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Cita", "Cita")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("InkManager.Core.Entities.MetricaDiaria", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkManager.Core.Entities.Estudio", "Estudio")
                        .WithMany()
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("InkManager.Core.Entities.PagoParcial", b =>
                {
                    b.HasOne("InkManager.Core.Entities.Cita", "Cita")
                        .WithMany("PagosParciales")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Artista", b =>
                {
                    b.Navigation("Asistentes");

                    b.Navigation("Citas");

                    b.Navigation("CubiculosAsignados");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Asistente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cita", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("PagosParciales");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Cliente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("InkManager.Core.Entities.Estudio", b =>
                {
                    b.Navigation("Artistas");

                    b.Navigation("ConfiguracionesCorreo");

                    b.Navigation("Cubiculos");
                });

            modelBuilder.Entity("InkManager.Core.Entities.ZonaCuerpo", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
